name: build-image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build docker image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build . -t colachen/shadowsocks-client-rpi:v`date +%Y%m%d` -t colachen/shadowsocks-client-rpi:latest
          docker push colachen/shadowsocks-client-rpi:v`date +%Y%m%d`
          docker push colachen/shadowsocks-client-rpi:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker run --rm colachen/shadowsocks-client-rpi ss-redir --help
          docker run --rm colachen/shadowsocks-client-rpi client_linux_arm7 --help
